### ISSUE TITLE
npm install has errors

### ISSUE THREAD

**Issue by caseyyee** [vr-components/vr-scene#4]
npm ERR! Error: No version provided
npm ERR!     at needVersion (/usr/local/lib/node_modules/npm/lib/cache/add-local-tarball.js:221:40)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache/add-local-tarball.js:158:12
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Darwin 14.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/casey/Developer/vr-scene
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.4.28
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/casey/Developer/vr-scene/npm-debug.log
npm ERR! not ok code 0

**Comment by caseyyee** [comment]
Removing `vr-components/vr-cube.git` from `devDependencies` in `package.json` clears the error, but I'm still unclear how to run the example locally.  It looks like the scripts are for some other projects.

The example also runs a bit differently than the example link in `README.md`

**Comment by caseyyee** [comment]
@dmacos has told me that none of these scripts are required to run the examples.    We should clean this up so someone coming to the repo/project understands what they need to do to get up and running.
